update_activity:
  name: Update Activity Settings
  description: Update the selected activity's settings
  target:
    entity:
      - integration: unfoldedcircle
        domain: switch
  fields:
    prevent_sleep:
      name: Prevent Sleep
      description: Toggle on to prevent the remote from sleeping when the activity is active.
      required: false
      selector:
        boolean:

learn_ir_command:
  name: Learn IR Commands
  description: Allows for the automated learning of a sequence of IR commands
  target:
    entity:
      - integration: unfoldedcircle
        domain: remote
  fields:
    remote:
      name: Remote Entity Information
      description: Remote Dictionary containing -> Name, Description, and Icon
      required: true
    ir_dataset:
      name: IR Codeset Information
      description: IR Codeset Dictionary containing -> Name and a list of commands
      required: true
