update_activity:
  name: Update Activity Settings
  description: Update the selected activity's settings
  target:
    entity:
      - integration: unfoldedcircle
        domain: switch
  fields:
    prevent_sleep:
      name: Prevent Sleep
      description: Toggle on to prevent the remote from sleeping when the activity is active.
      required: false
      selector:
        boolean:

learn_ir_command:
  name: Learn IR Commands
  description: Allows for the automated learning of a sequence of IR commands
  target:
    entity:
      - integration: unfoldedcircle
        domain: remote
  fields:
    remote:
      name: Remote Entity Information
      description: Remote Dictionary containing -> Name, Description, and Icon
      required: true
    ir_dataset:
      name: IR Codeset Information
      description: IR Codeset Dictionary containing -> Name and a list of commands
      required: true

send_ir_command:
  name: Send IR Commands
  description: Allows for the automated sending of a sequence of IR commands
  target:
    entity:
      - integration: unfoldedcircle
        domain: remote
  fields:
    device:
      name: Device Name / Manufacturer
      description: Custom Codeset Device Name / Manufacturer
      required: true
      selector:
        text:
    codeset:
      name: Manufacturer Codeset Name
      description: The name of the manufacturer codeset
      required: false
      selector:
        text:
    command:
      name: IR Command
      description: Predefined IR command
      required: true
      selector:
          text:
    num_repeats:
      name: Repeat Count
      description: Number of times to repeat sending the command
      required: false
      selector:
        number:
          min: 0
          max: 20
          unit_of_measurement: times
          mode: box
    dock:
      name: Dock Name
      description: The name of the Dock to send the command to
      required: false
      selector:
        text:
    port:
      name: Dock Port
      description: The port to send the command to
      required: false
      selector:
        select:
          options:
            - "Dock Top"
            - "Dock Bottom"
            - "Ext 1"
            - "Ext 2"
            - "Ext 1 & 2"
            - "Dock Bottom & Ext 1"
            - "Dock Bottom & Ext 2"

send_button_command:
  name: Send Button Commands
  description: Allows for the automated sending of a sequence of predefined button commands
  target:
    entity:
      - integration: unfoldedcircle
        domain: remote
  fields:
    command:
      name: Remote button Name
      description: Refer to documentation for list of valid button names
      required: true
      selector:
          text:
    activity:
      name: Acitvity Name
      description: Activity name to send the command to (Only needed if multiple activities are running)
      required: true
      selector:
          text:
    num_repeats:
      name: Repeat Count
      description: Number of times to repeat sending the command
      required: false
      selector:
        number:
          min: 0
          max: 20
          unit_of_measurement: times
          mode: box
    delay_secs:
      name: Delay seconds
      description: The time you want to wait in between repeated commands
      required: false
      selector:
        number:
          min: 0
          max: 20
          unit_of_measurement: seconds
          mode: box
    hold:
      name: Hold
      description: Perform a long press of the specified button
      required: false
      selector:
        boolean:
