#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
python3 -m pip install --disable-pip-version-check \
    --requirement requirements_all.txt \
    --requirement requirements_dev.txt \
    --upgrade

mkdir -p config
