#!/usr/bin/env bash
sudo apt-get update && sudo apt-get install -y libturbojpeg0 autoconf automake libtool
set -e
cd "$(dirname "$0")/.."
python3 -m pip install --requirement requirements_all.txt --upgrade
pre-commit install
mkdir -p config